# Site settings
store_name: Tuileries
store_address_street: 43155 Main Street
store_address_suite: Suite 210
store_city_state: Novi, MI 48375
title: Tuileries
email: your-email@domain.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Tuileries

# Build settings
markdown: kramdown
permalink: pretty
